spring.application.name=Nadeulirang
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.schema=nadeulirang
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'Asia/Seoul'
spring.sql.init.mode=never
spring.flyway.default-schema=nadeulirang
spring.flyway.schemas=nadeulirang
spring.flyway.clean-disabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoint.health.show-components=never
management.endpoint.health.probes.enabled=false
